import os
import datetime
import ipaddress
from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.x509.oid import NameOID
from cryptography.exceptions import InvalidSignature

class CryptoUtils:
    STORAGE_DIR = "ca_storage"

    # ... (verify_cert_signature remains the same) ...
    @staticmethod
    def verify_cert_signature(cert_path, issuer_cert_path):
        """Verifies that cert was signed by issuer_cert."""
        cert = CryptoUtils.load_cert(cert_path)
        issuer_cert = CryptoUtils.load_cert(issuer_cert_path)
        
        public_key = issuer_cert.public_key()
        
        try:
            public_key.verify(
                cert.signature,
                cert.tbs_certificate_bytes,
                padding.PKCS1v15(), # Assuming RSA signatures generated by this tool
                cert.signature_hash_algorithm,
            )
            return True, "Signature is valid."
        except InvalidSignature:
            return False, "Invalid Signature."
        except Exception as e:
            return False, f"Verification Error: {str(e)}"

    @staticmethod
    def get_cert_details(filename):
        """Parses a certificate and returns a dict of details."""
        try:
            cert = CryptoUtils.load_cert(filename)
            
            details = {
                'subject': cert.subject.rfc4514_string(),
                'issuer': cert.issuer.rfc4514_string(),
                'serial_number': cert.serial_number,
                'not_valid_before': cert.not_valid_before.strftime('%Y-%m-%d %H:%M:%S'),
                'not_valid_after': cert.not_valid_after.strftime('%Y-%m-%d %H:%M:%S'),
                'version': cert.version.name,
                'fingerprint_sha256': cert.fingerprint(hashes.SHA256()).hex(),
                'sans': [],
                'is_ca': False
            }

            # Parse Extensions
            try:
                bc = cert.extensions.get_extension_for_class(x509.BasicConstraints)
                details['is_ca'] = bc.value.ca
            except x509.ExtensionNotFound:
                pass

            try:
                san = cert.extensions.get_extension_for_class(x509.SubjectAlternativeName)
                for name in san.value:
                    if isinstance(name, x509.DNSName):
                        details['sans'].append(f"DNS: {name.value}")
                    elif isinstance(name, x509.IPAddress):
                        details['sans'].append(f"IP: {name.value}")
                    else:
                        details['sans'].append(f"Other: {name.value}")
            except x509.ExtensionNotFound:
                pass

            return details
        except Exception as e:
            return None

    @classmethod
    def ensure_storage(cls):
        if not os.path.exists(cls.STORAGE_DIR):
            os.makedirs(cls.STORAGE_DIR)

    @staticmethod
    def generate_key(key_size=2048):
        """Generates a private key."""
        return rsa.generate_private_key(
            public_exponent=65537,
            key_size=key_size,
        )

    # ... save_key, save_cert, load_key, load_cert ...
    @staticmethod
    def save_key(key, filename):
        """Saves a private key to disk."""
        CryptoUtils.ensure_storage()
        path = os.path.join(CryptoUtils.STORAGE_DIR, filename)
        with open(path, "wb") as f:
            f.write(key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.TraditionalOpenSSL,
                encryption_algorithm=serialization.NoEncryption(),
            ))
        return path

    @staticmethod
    def save_cert(cert, filename):
        """Saves a certificate to disk."""
        CryptoUtils.ensure_storage()
        path = os.path.join(CryptoUtils.STORAGE_DIR, filename)
        with open(path, "wb") as f:
            f.write(cert.public_bytes(serialization.Encoding.PEM))
        return path
    
    @staticmethod
    def load_key(filename):
        path = os.path.join(CryptoUtils.STORAGE_DIR, filename)
        with open(path, "rb") as f:
            return serialization.load_pem_private_key(f.read(), password=None)

    @staticmethod
    def load_cert(filename):
        path = os.path.join(CryptoUtils.STORAGE_DIR, filename)
        with open(path, "rb") as f:
            return x509.load_pem_x509_certificate(f.read())

    @staticmethod
    def create_root_ca(common_name, organization, country, valid_days=3650):
        """Creates a self-signed Root CA."""
        key = CryptoUtils.generate_key()
        
        subject = issuer = x509.Name([
            x509.NameAttribute(NameOID.COUNTRY_NAME, country),
            x509.NameAttribute(NameOID.ORGANIZATION_NAME, organization),
            x509.NameAttribute(NameOID.COMMON_NAME, common_name),
        ])

        cert_builder = x509.CertificateBuilder().subject_name(
            subject
        ).issuer_name(
            issuer
        ).public_key(
            key.public_key()
        ).serial_number(
            x509.random_serial_number()
        ).not_valid_before(
            datetime.datetime.utcnow()
        ).not_valid_after(
            datetime.datetime.utcnow() + datetime.timedelta(days=valid_days)
        ).add_extension(
            x509.BasicConstraints(ca=True, path_length=None), critical=True,
        )

        cert = cert_builder.sign(key, hashes.SHA256())
        return key, cert

    @staticmethod
    def create_csr(common_name, organization, country, sans=None):
        """Generates a Private Key and a CSR."""
        key = CryptoUtils.generate_key()
        builder = x509.CertificateSigningRequestBuilder().subject_name(x509.Name([
            x509.NameAttribute(NameOID.COUNTRY_NAME, country),
            x509.NameAttribute(NameOID.ORGANIZATION_NAME, organization),
            x509.NameAttribute(NameOID.COMMON_NAME, common_name),
        ]))

        # Add Basic Constraints
        builder = builder.add_extension(
            x509.BasicConstraints(ca=True, path_length=0), critical=True,
        )

        # Add SANs if provided
        if sans:
            san_list = []
            for s in sans:
                s = s.strip()
                try:
                    # Check if it's an IP
                    ip_addr = ipaddress.ip_address(s)
                    san_list.append(x509.IPAddress(ip_addr))
                except ValueError:
                    # Not an IP, assume DNS
                    san_list.append(x509.DNSName(s))
            
            builder = builder.add_extension(
                x509.SubjectAlternativeName(san_list), critical=False
            )

        csr = builder.sign(key, hashes.SHA256())
        return key, csr

    @staticmethod
    def sign_csr(csr_pem, ca_cert_path, ca_key_path, valid_days=365, is_ca=False):
        """Signs a CSR with the given CA."""
        ca_cert = CryptoUtils.load_cert(ca_cert_path)
        ca_key = CryptoUtils.load_key(ca_key_path)
        
        csr = x509.load_pem_x509_csr(csr_pem.encode('utf-8'))

        builder = x509.CertificateBuilder().subject_name(
            csr.subject
        ).issuer_name(
            ca_cert.subject
        ).public_key(
            csr.public_key()
        ).serial_number(
            x509.random_serial_number()
        ).not_valid_before(
            datetime.datetime.utcnow()
        ).not_valid_after(
            datetime.datetime.utcnow() + datetime.timedelta(days=valid_days)
        )

        # If it's an Intermediate CA, we need BasicConstraints CA=TRUE
        # If it's a leaf, CA=FALSE
        builder = builder.add_extension(
            x509.BasicConstraints(ca=is_ca, path_length=None), critical=True,
        )

        # Copy SubjectAlternativeName extension if present
        try:
            san_ext = csr.extensions.get_extension_for_class(x509.SubjectAlternativeName)
            builder = builder.add_extension(san_ext.value, critical=san_ext.critical)
        except x509.ExtensionNotFound:
            pass

        cert = builder.sign(ca_key, hashes.SHA256())
        return cert
